#!/usr/bin/env php
<?php

require_once 'init.php';

$helpers = array(
	'dm' => new Doctrine\ODM\MongoDB\Tools\Console\Helper\DocumentManagerHelper($container->get('odm')),
);

$helperSet = isset($helperSet) ? $helperSet : new \Symfony\Component\Console\Helper\HelperSet();
foreach ($helpers as $name => $helper) {
	$helperSet->set($helper, $name);
}

$app = new Symfony\Component\Console\Application('Doctrine ODM MongoDB Command Line Interface', Doctrine\ODM\MongoDB\Version::VERSION);
$app->setCatchExceptions(true);
$app->setHelperSet($helperSet);
$app->addCommands(array(
	new \Fuga\Component\Install\FixCommand(),
	new \Fuga\Component\Install\ConfigCommand(),
	new \Doctrine\ODM\MongoDB\Tools\Console\Command\QueryCommand(),
	new \Doctrine\ODM\MongoDB\Tools\Console\Command\GenerateDocumentsCommand(),
	new \Doctrine\ODM\MongoDB\Tools\Console\Command\GenerateRepositoriesCommand(),
	new \Doctrine\ODM\MongoDB\Tools\Console\Command\GenerateProxiesCommand(),
	new \Doctrine\ODM\MongoDB\Tools\Console\Command\GenerateHydratorsCommand(),
	new \Doctrine\ODM\MongoDB\Tools\Console\Command\ClearCache\MetadataCommand(),
	new \Doctrine\ODM\MongoDB\Tools\Console\Command\Schema\CreateCommand(),
	new \Doctrine\ODM\MongoDB\Tools\Console\Command\Schema\DropCommand(),
));
$app->run();